language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
   - PHPBB_TAG="release-3.3.3"
   - PHPBB_VERSION="3.3"
   - PHPBB_LANGUAGE="el"

before_install:
  - mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE
  - mkdir -p $PHPBB_VERSION/en/language
  - mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
  - mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
  - mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
  - git clone --branch $PHPBB_TAG "https://github.com/phpbb/phpbb.git"
  - mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language
  - mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
  - travis_retry composer self-update
  - travis_retry curl -s http://getcomposer.org/installer | php
  
install:
  - travis_retry php composer.phar install --dev --no-interaction --prefer-source
 
script:
  - php vendor/bin/translation.php validate $PHPBB_LANGUAGE --phpbb-version=$PHPBB_VERSION --display-notices
  
